export const backpacksConstants = {
  GETALL_REQUEST: 'BACKPACKS_GETALL_REQUEST',
  GETALL_SUCCESS: 'BACKPACKS_GETALL_SUCCESS',
  GETALL_FAILURE: 'BACKPACKS_GETALL_FAILURE',

  ADD_REQUEST: 'BACKPACKS_ADD_REQUEST',
  ADD_SUCCESS: 'BACKPACKS_ADD_SUCCESS',
  ADD_FAILURE: 'BACKPACKS_ADD_FAILURE',

  DELETE_REQUEST: 'BACKPACKS_DELETE_REQUEST',
  DELETE_SUCCESS: 'BACKPACKS_DELETE_SUCCESS',
  DELETE_FAILURE: 'BACKPACKS_DELETE_FAILURE',
};
