export const backpackUserConstants = {
  GET_REQUEST: 'USER_GET_REQUEST',
  GET_SUCCESS: 'USER_GET_SUCCESS',
  CLEAR_ALL: 'USER_CLEAR_ALL',

  ADD_REQUEST: 'USER_ADD_REQUEST',
  ADD_SUCCESS: 'USER_POST_SUCCESS',

  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',

  DELETE_REQUEST: 'USER_DELETE_REQUEST',
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
};
