export const collectionsConstants = {
  GET_ALL: 'COLLECTION_GET_ALL',
  CLEAR_ALL: 'COLLECTION_CLEAR_ALL',

  ADD_COLLECTION_REQUEST: 'COLLECTION_ADD_COLLECTION_REQUEST',
  ADD_COLLECTION_SUCCESS: 'COLLECTION_ADD_COLLECTION_SUCCESS',

  GET_REQUEST: 'COLLECTION_GET_REQUEST',
  GET_SUCCESS: 'COLLECTION_GET_SUCCESS',

  ADD_REQUEST: 'COLLECTION_ADD_REQUEST',
  ADD_SUCCESS: 'COLLECTION_POST_SUCCESS',

  UPDATE_REQUEST: 'COLLECTION_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'COLLECTION_PATCH_SUCCESS',

  REPLACE_REQUEST: 'COLLECTION_REPLACE_REQUEST',
  REPLACE_SUCCESS: 'COLLECTION_PUT_SUCCESS',

  DELETE_REQUEST: 'COLLECTION_DELETE_REQUEST',
  DELETE_SUCCESS: 'COLLECTION_DELETE_SUCCESS',
};
