export const collectionsConstants = {
  GET_ALL: 'COLLECTION_GET_ALL',
  CLEAR_ALL: 'COLLECTION_CLEAR_ALL',

  GET_REQUEST: 'COLLECTION_GET_REQUEST',
  GET_SUCCESS: 'COLLECTION_GET_SUCCESS',

  UPDATE_REQUEST: 'COLLECTION_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'COLLECTION_PATCH_SUCCESS',

  DELETE_REQUEST: 'COLLECTION_DELETE_REQUEST',
  DELETE_SUCCESS: 'COLLECTION_DELETE_SUCCESS',
};
