export const deployConstants = {
  DEPLOY_UPLOAD_STARTED: 'DEPLOY_UPLOAD_STARTED',
  DEPLOY_UPLOAD_COMPLETED: 'DEPLOY_UPLOAD_COMPLETED',
  DEPLOY_DEPLOYMENT_COMPLETE: 'DEPLOY_DEPLOYMENT_COMPLETE',
  DEPLOY_ALLOCATED_SSL: 'DEPLOY_ALLOCATED_SSL',
  DEPLOY_COMPLETED: 'DEPLOY_COMPLETED',
  DEPLOY_FAILED: 'DEPLOY_FAILED',

  NOT_DEPLOYING_STATUS: 0,
  UPLOADING_STATUS: 1,
  DEPLOYING_STATUS: 2,
  ALLOCATING_SSL_STATUS: 3,
  ALLOCATED_SSL_STATUS: 4,
  COMPLETE_STATUS: 5,
};
