export const websocketConstants = {
  CONNECT: 'WS_CONNECT',
  CONNECTED: 'WS_CONNECTED',
  DISCONNECT: 'WS_DISCONNECT',

  CONNECTION_LOST: 'WS_CONNECTION_LOST',

  SEND: 'WS_SEND',
  FAILURE: 'WS_FAILURE',

  CONNECTED_STATUS: 'CONNECTED',
  CONNECTING_STATUS: 'CONNECTING',
  RECONNECTING_STATUS: 'RECONNECTING',
  CONNECTION_LOST_STATUS: 'CONNECTION_LOST',
  DISCONNECTED_STATUS: 'DISCONNECTED',
};
